trigger: none

variables:
  - template: "/.azuredevops/pipelineVariables/global.variables.yml"
  - group: "Network-TrafficManager-Variables"

stages:
  # Networking connectivity deployment
  - template: /.azuredevops/pipelineTemplates/main.yml
    parameters:
      targetEnvironment: $(targetEnvironment)
      subscriptionId: $(subscriptionId)
  #   managementGroupId: $(managementGroupId)
  #   tenantId: 'xxxx-xxxx-xxx-xxxx'
  #   deploymentSpId: 'xxxx-xxxx-xxx-xxxx'
  #   resourceGroupName: 'xxxx-xxxx-xxx-xxxx'
      deploymentBlocks:
        - Path: deployment/networking/tm-basculas-operativa-clientes-prod
          templateFilePath: main.bicep # Should only be specified if not deploy.bicep or deploy.json
          parametersPath: main.bicepparam
          jobName: Basculas_Operativa_Clientes_Networking_Traffic_Manager_Deployment
          displayName: 'Basculas Operativa Clientes Azure Networking Traffic Manager Deployment'
          # customParameterFileTokens: '{"tokenName":"tokenValue"}'
          # prereqScript: prereqs.ps1
          # postDeploymentScript: postDeployment.ps1