# ============================================================================
# EXAMPLE: Pull Request Validation Pipeline
# ============================================================================
# This pipeline validates Bicep templates for pull requests
# Does not deploy, only validates and provides feedback
# ============================================================================

name: PR-Validation-$(System.PullRequest.PullRequestId)

# Only run on PRs
trigger: none

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - applications/**
      - modules/**
      - config/**

variables:
  - group: 'bicep-dev'  # Use dev credentials for validation
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: azureLocation
    value: 'eastus'

stages:
  - stage: PR_Validation
    displayName: 'Pull Request Validation'
    
    jobs:
      # Lint all Bicep files
      - job: Lint_Bicep
        displayName: 'Lint Bicep Files'
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            displayName: 'Get Changed Files'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Getting changed files in PR..."
                
                # Get the list of changed files
                git diff --name-only origin/$(System.PullRequest.TargetBranch) > changed-files.txt
                
                echo "Changed files:"
                cat changed-files.txt
                
                # Filter for .bicep files
                grep "\.bicep$" changed-files.txt > bicep-files.txt || true
                
                if [ -s bicep-files.txt ]; then
                  echo ""
                  echo "Bicep files to validate:"
                  cat bicep-files.txt
                else
                  echo ""
                  echo "No Bicep files changed in this PR"
                fi
          
          - task: AzureCLI@2
            displayName: 'Lint Changed Bicep Files'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "==============================================="
                echo "Linting Changed Bicep Files"
                echo "==============================================="
                
                if [ ! -s bicep-files.txt ]; then
                  echo "No Bicep files to lint"
                  exit 0
                fi
                
                LINT_FAILED=0
                
                while IFS= read -r bicep_file; do
                  if [ -f "$bicep_file" ]; then
                    echo ""
                    echo "Linting: $bicep_file"
                    echo "-----------------------------------------------"
                    
                    if az bicep build --file "$bicep_file" --stdout > /dev/null 2>&1; then
                      echo "âœ“ $bicep_file - PASSED"
                    else
                      echo "âœ— $bicep_file - FAILED"
                      az bicep build --file "$bicep_file" || true
                      LINT_FAILED=1
                    fi
                  fi
                done < bicep-files.txt
                
                echo ""
                if [ $LINT_FAILED -eq 1 ]; then
                  echo "âœ— Linting failed for one or more files"
                  exit 1
                else
                  echo "âœ“ All files passed linting"
                fi
      
      # Validate templates for each environment
      - job: Validate_Templates
        displayName: 'Validate Templates'
        dependsOn: Lint_Bicep
        pool:
          vmImage: $(vmImageName)
        
        strategy:
          matrix:
            Dev:
              environmentName: 'dev'
              serviceConnection: $(azureServiceConnection-dev)
            Test:
              environmentName: 'test'
              serviceConnection: $(azureServiceConnection-test)
            UAT:
              environmentName: 'uat'
              serviceConnection: $(azureServiceConnection-uat)
            Prod:
              environmentName: 'prod'
              serviceConnection: $(azureServiceConnection-prod)
        
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            displayName: 'Validate for $(environmentName)'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Validating template for $(environmentName) environment..."
                
                # Check if main.bicep exists
                MAIN_TEMPLATE="applications/step/main.bicep"
                PARAM_FILE="applications/step/$(environmentName)/$(environmentName).bicepparam"
                
                if [ ! -f "$MAIN_TEMPLATE" ]; then
                  echo "Main template not found, skipping validation"
                  exit 0
                fi
                
                if [ ! -f "$PARAM_FILE" ]; then
                  echo "Parameter file not found for $(environmentName), skipping"
                  exit 0
                fi
                
                echo "Validating deployment..."
                az deployment sub validate \
                  --location $(azureLocation) \
                  --template-file "$MAIN_TEMPLATE" \
                  --parameters "$PARAM_FILE"
                
                if [ $? -eq 0 ]; then
                  echo "âœ“ Validation passed for $(environmentName)"
                else
                  echo "âœ— Validation failed for $(environmentName)"
                  exit 1
                fi
      
      # Run What-If for affected environments
      - job: What_If_Analysis
        displayName: 'What-If Analysis'
        dependsOn: Validate_Templates
        condition: succeeded()
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            displayName: 'What-If for Dev'
            inputs:
              azureSubscription: $(azureServiceConnection-dev)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running what-if analysis for dev environment..."
                
                MAIN_TEMPLATE="applications/step/main.bicep"
                PARAM_FILE="applications/step/dev/dev.bicepparam"
                
                if [ -f "$MAIN_TEMPLATE" ] && [ -f "$PARAM_FILE" ]; then
                  az deployment sub what-if \
                    --location $(azureLocation) \
                    --template-file "$MAIN_TEMPLATE" \
                    --parameters "$PARAM_FILE" \
                    --result-format ResourceIdOnly
                  
                  echo ""
                  echo "âœ“ What-if analysis completed"
                else
                  echo "Templates not found, skipping what-if"
                fi
      
      # Publish PR comment with results
      - job: Publish_Results
        displayName: 'Publish Validation Results'
        dependsOn:
          - Lint_Bicep
          - Validate_Templates
          - What_If_Analysis
        condition: always()
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - checkout: self
          
          - task: PowerShell@2
            displayName: 'Generate PR Comment'
            inputs:
              targetType: 'inline'
              script: |
                $lintStatus = "$env:LINT_RESULT"
                $validateStatus = "$env:VALIDATE_RESULT"
                $whatifStatus = "$env:WHATIF_RESULT"
                
                $comment = @"
                ## ðŸ” Bicep Validation Results
                
                **PR:** #$(System.PullRequest.PullRequestId)
                **Build:** [$(Build.BuildNumber)]($(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId))
                
                ### Results Summary
                
                | Stage | Result |
                |-------|--------|
                | Linting | $lintStatus |
                | Validation | $validateStatus |
                | What-If | $whatifStatus |
                
                ### Next Steps
                
                - Review the what-if analysis to understand the changes
                - Ensure all tests pass before merging
                - Get required approvals
                
                ---
                *Automated validation by Azure DevOps*
                "@
                
                Write-Host $comment
                
                # Save for potential use by PR comment task
                $comment | Out-File -FilePath pr-comment.md
            env:
              LINT_RESULT: ${{ eq(dependencies.Lint_Bicep.result, 'Succeeded') && 'âœ“ Passed' || 'âœ— Failed' }}
              VALIDATE_RESULT: ${{ eq(dependencies.Validate_Templates.result, 'Succeeded') && 'âœ“ Passed' || 'âœ— Failed' }}
              WHATIF_RESULT: ${{ eq(dependencies.What_If_Analysis.result, 'Succeeded') && 'âœ“ Passed' || 'âœ— Failed' }}